# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'model_quali.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Model_quali(object):
    def setupUi(self, Model_quali):
        Model_quali.setObjectName("Model_quali")
        Model_quali.resize(891, 432)
        self.gridLayout = QtWidgets.QGridLayout(Model_quali)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(Model_quali)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Model_quali)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.LogiR_use = QtWidgets.QCheckBox(Model_quali)
        self.LogiR_use.setObjectName("LogiR_use")
        self.verticalLayout_3.addWidget(self.LogiR_use, 0, QtCore.Qt.AlignHCenter)
        self.LogiR_auto = QtWidgets.QCheckBox(Model_quali)
        self.LogiR_auto.setObjectName("LogiR_auto")
        self.verticalLayout_3.addWidget(self.LogiR_auto, 0, QtCore.Qt.AlignHCenter)
        self.label_10 = QtWidgets.QLabel(Model_quali)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(Model_quali)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.combo_penality = QtWidgets.QComboBox(Model_quali)
        self.combo_penality.setObjectName("combo_penality")
        self.combo_penality.addItem("")
        self.combo_penality.addItem("")
        self.combo_penality.addItem("")
        self.horizontalLayout_8.addWidget(self.combo_penality)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(Model_quali)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.LogiR_C = QtWidgets.QLineEdit(Model_quali)
        self.LogiR_C.setObjectName("LogiR_C")
        self.horizontalLayout_4.addWidget(self.LogiR_C)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Model_quali)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Model_quali)
        self.label.setMaximumSize(QtCore.QSize(16777215, 67))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.RT_use = QtWidgets.QCheckBox(Model_quali)
        self.RT_use.setObjectName("RT_use")
        self.verticalLayout_4.addWidget(self.RT_use, 0, QtCore.Qt.AlignHCenter)
        self.RT_auto = QtWidgets.QCheckBox(Model_quali)
        self.RT_auto.setObjectName("RT_auto")
        self.verticalLayout_4.addWidget(self.RT_auto, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(Model_quali)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(Model_quali)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.combo_criterion = QtWidgets.QComboBox(Model_quali)
        self.combo_criterion.setObjectName("combo_criterion")
        self.combo_criterion.addItem("")
        self.combo_criterion.addItem("")
        self.combo_criterion.addItem("")
        self.horizontalLayout_5.addWidget(self.combo_criterion)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(Model_quali)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.RT_mss = QtWidgets.QLineEdit(Model_quali)
        self.RT_mss.setObjectName("RT_mss")
        self.horizontalLayout_6.addWidget(self.RT_mss)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(Model_quali)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.RT_mse = QtWidgets.QLineEdit(Model_quali)
        self.RT_mse.setObjectName("RT_mse")
        self.horizontalLayout_7.addWidget(self.RT_mse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.KNN_use = QtWidgets.QCheckBox(Model_quali)
        self.KNN_use.setObjectName("KNN_use")
        self.verticalLayout.addWidget(self.KNN_use, 0, QtCore.Qt.AlignHCenter)
        self.KNN_auto = QtWidgets.QCheckBox(Model_quali)
        self.KNN_auto.setObjectName("KNN_auto")
        self.verticalLayout.addWidget(self.KNN_auto, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(Model_quali)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(Model_quali)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6, 0, QtCore.Qt.AlignLeft)
        self.combo_metric = QtWidgets.QComboBox(Model_quali)
        self.combo_metric.setObjectName("combo_metric")
        self.combo_metric.addItem("")
        self.combo_metric.addItem("")
        self.combo_metric.addItem("")
        self.combo_metric.addItem("")
        self.horizontalLayout_3.addWidget(self.combo_metric, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(Model_quali)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15, 0, QtCore.Qt.AlignLeft)
        self.combo_p = QtWidgets.QComboBox(Model_quali)
        self.combo_p.setObjectName("combo_p")
        self.combo_p.addItem("")
        self.combo_p.addItem("")
        self.horizontalLayout_11.addWidget(self.combo_p, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Model_quali)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.KNN_leafsize = QtWidgets.QLineEdit(Model_quali)
        self.KNN_leafsize.setObjectName("KNN_leafsize")
        self.horizontalLayout.addWidget(self.KNN_leafsize)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(Model_quali)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.KNN_n = QtWidgets.QLineEdit(Model_quali)
        self.KNN_n.setObjectName("KNN_n")
        self.horizontalLayout_2.addWidget(self.KNN_n)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)

        self.retranslateUi(Model_quali)
        self.buttonBox.accepted.connect(Model_quali.accept)
        self.buttonBox.rejected.connect(Model_quali.reject)
        QtCore.QMetaObject.connectSlotsByName(Model_quali)

    def retranslateUi(self, Model_quali):
        _translate = QtCore.QCoreApplication.translate
        Model_quali.setWindowTitle(_translate("Model_quali", "Model Menu"))
        self.label_7.setText(_translate("Model_quali", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">Regression Tree</span></p></body></html>"))
        self.LogiR_use.setText(_translate("Model_quali", "Use ?"))
        self.LogiR_auto.setText(_translate("Model_quali", "Auto "))
        self.label_10.setText(_translate("Model_quali", "Hyperparamètre :"))
        self.label_14.setText(_translate("Model_quali", "penality :"))
        self.combo_penality.setItemText(0, _translate("Model_quali", "l1"))
        self.combo_penality.setItemText(1, _translate("Model_quali", "l2"))
        self.combo_penality.setItemText(2, _translate("Model_quali", "elasticnet"))
        self.label_8.setText(_translate("Model_quali", "C:"))
        self.label_2.setText(_translate("Model_quali", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">K Neigbors Classifier </span></p></body></html>"))
        self.label.setText(_translate("Model_quali", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; font-weight:600; text-decoration: underline;\">Logistic Regression</span></p></body></html>"))
        self.RT_use.setText(_translate("Model_quali", "Use ?"))
        self.RT_auto.setText(_translate("Model_quali", "Auto "))
        self.label_9.setText(_translate("Model_quali", "Hyperparamètre :"))
        self.label_11.setText(_translate("Model_quali", "<html><head/><body><p align=\"center\">Criterion:</p></body></html>"))
        self.combo_criterion.setItemText(0, _translate("Model_quali", "mse"))
        self.combo_criterion.setItemText(1, _translate("Model_quali", "friedman_mse"))
        self.combo_criterion.setItemText(2, _translate("Model_quali", "mae"))
        self.label_12.setText(_translate("Model_quali", "min samples split :"))
        self.label_13.setText(_translate("Model_quali", "min samples leaf :"))
        self.KNN_use.setText(_translate("Model_quali", "Use ?"))
        self.KNN_auto.setText(_translate("Model_quali", "Auto "))
        self.label_3.setText(_translate("Model_quali", "Hyperparamètre :"))
        self.label_6.setText(_translate("Model_quali", "<html><head/><body><p align=\"center\">Metric:</p></body></html>"))
        self.combo_metric.setItemText(0, _translate("Model_quali", "euclidean"))
        self.combo_metric.setItemText(1, _translate("Model_quali", "manhattan"))
        self.combo_metric.setItemText(2, _translate("Model_quali", "chebyshev"))
        self.combo_metric.setItemText(3, _translate("Model_quali", "minkowski"))
        self.label_15.setText(_translate("Model_quali", "p :"))
        self.combo_p.setItemText(0, _translate("Model_quali", "1"))
        self.combo_p.setItemText(1, _translate("Model_quali", "2"))
        self.label_4.setText(_translate("Model_quali", "Leaf Size :"))
        self.label_5.setText(_translate("Model_quali", "n_neighbors :"))

